version: '3.8'
services:
  fastapi:
    image: fastapi-sentiment-server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    volumes:
      - /mnt/d/MLOps2/test_data.csv:/app/test_data.csv
      - /mnt/d/MLOps2/latest_runs.json:/app/latest_runs.json
      - /mnt/d/MLOps2/model_pipeline/mlruns:/mnt/d/MLOps2/model_pipeline/mlruns
      - /mnt/d/MLOps2/model_pipeline/mlruns:/app/mlruns
    container_name: fastapi-server