services:
  fastapi:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    environment:
      MLFLOW_TRACKING_URI: ${DOCKER_MLFLOW_TRACKING_URI:-http://host.docker.internal:5000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: fastapi-server
