name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dockerfiles/requirements.txt
          pip install pytest  # Đảm bảo pytest có trên runner để debug nếu cần
          pip install pytest-mock
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: |
          cd dockerfiles
          docker compose build fastapi
          docker compose up -d
          echo "Waiting for FastAPI to start..."
          sleep 15
          docker compose logs fastapi > server_logs.txt 2>&1
          docker compose exec -T fastapi pytest test.py
          cat server_logs.txt  # In log ra để debug
          docker compose down

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with Docker Compose
        run: |
          cd dockerfiles
          docker compose build fastapi
          docker save -o fastapi.tar $(docker images dockerfiles-fastapi -q)
          docker load -i fastapi.tar
          docker tag dockerfiles-fastapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/twitter_analysis:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/twitter_analysis:latest